all: draw/draw image/image input/input icon/icon

draw/draw: draw/draw.c
	$(CC) $^ -o draw/draw -lg13

image/image: image/image.c
	$(CC) $^ -o image/image -lg13

input/input: input/input.c
	$(CC) $^ -o input/input -lg13

icon/icon: icon/icon.c
	$(CC) $^ -o icon/icon -lg13
